name: Python Tests

on:
  push:
    branches:
      - "*"
  pull_request:
    branches:
      - "*"

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Check out the code
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Install system packages
      - name: Install system packages
        run: |
          sudo apt-get update
          sudo apt-get install -y ffmpeg libxml2-dev libxslt1-dev

      # Step 3: Set up Python
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'

      - name: Check Torch Cache Directory
        run: |
          echo "Torch cache directory: $HOME/.cache/torch"
          ls -al $HOME/.cache/torch || echo "Torch cache directory does not exist yet."
          mkdir -p $HOME/.cache/torch/pyannote

      # Step 4: Install transcriber
      - name: Install transcriber
        run: |
          python -m pip install --upgrade pip
          pip install pytest
          pip install --no-cache-dir -U "huggingface_hub[cli]"
          mkdir -p "${{ github.workspace }}/.cache/torch/pyannote"
          huggingface-cli login --token ${{ secrets.HF_TOKEN }}
          huggingface-cli download pyannote/speaker-diarization-3.1 --cache-dir $HOME/.cache/torch/pyannote
          huggingface-cli download pyannote/segmentation-3.0 --cache-dir $HOME/.cache/torch/pyannote
          pip install --no-cache-dir numpy==1.26.4
          pip install --no-cache-dir faster-whisper==1.0.0
          pip install --no-cache-dir -r "${{ github.workspace }}/requirements.txt"
          pip install --no-cache-dir -e "${{ github.workspace }}"

      # Step 5: Run test suite
      - name: Run test suite
        run: |
          cd "${{ github.workspace }}/tests"
          chmod +x run_test_suite.sh  # Ensure the script is executable
          ./run_test_suite.sh